 apiVersion: v1  
 kind: PersistentVolumeClaim  
 metadata:  
  name: compose-post-redis-pvc
  namespace: social-network
 spec:  
  storageClassName: openebs-hostpath
  accessModes:  
   - ReadWriteOnce
  resources:  
   requests:  
    storage: 1Gi

